config/routes.rb
Booday10::Application.routes.draw do

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  root 'pins#index'
  get 'soccer' => 'pins#soccer'
  get 'basket_ball' => 'pins#basket_ball'
  get 'login' => 'sessions#new'
  get 'signup' => 'users#new'
  post 'login' => 'sessions#create'
  post 'signup' => 'users#create'
  delete 'logout' => 'sessions#destroy'
    
  resources :users
  resources :pins
  # resources :pins do
  #   member do
  #     put "like" => "pins#like"
  #     put "dislike" => "pins#dislike"
  #   end
  # end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/pin.rb
class Pin < ActiveRecord::Base
  
  self.per_page = 16
  # acts_as_votable
  belongs_to :user
  belongs_to :category
  validates :title, presence: true
  validates :category_id, presence: true
  validates :content, presence: true, length: { maximum: 3000 }
  
  # has_attached_file :image, styles: { large: "700x700>", medium: "300x300>", small: "100x100#", thumb: "300x180#" }
  has_attached_file :image, styles: { large: "700x700>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  # validates :image, attachment_presence: true

  def self.search(search)
    where("title LIKE ? OR content LIKE ?", "%#{search}%", "%#{search}%") 
  end

  # Prettifies the URLs
  def to_param
    "#{id} #{title[0,10]}".parameterize
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController

  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_pin, only: [:edit, :update, :destroy]

  def index
    current_page = params[:page] || 1
    per_page = params[:per_page] || 16
    @pins = Pin.order('created_at DESC')

    if params[:search] && !params[:search].blank?
      @pins = Pin.search(params[:search])
      users = User.search(params[:search])
      unless users.blank?
        users.each do |user|
          @pins += user.pins
        end
      end
    end

    length = @pins.length

    @pins = WillPaginate::Collection.create(current_page, per_page, length) do |pager|
      pager.replace @pins[pager.offset, pager.per_page].to_a
    end
  end

  def soccer
    current_page = params[:page] || 1
    per_page = params[:per_page] || 16
    @pins = Pin.where(category_id: 2).order('created_at DESC')
    length = @pins.length

    @pins = WillPaginate::Collection.create(current_page, per_page, length) do |pager|
      pager.replace @pins[pager.offset, pager.per_page].to_a
    end
  end

  def basket_ball
    current_page = params[:page] || 1
    per_page = params[:per_page] || 16
    @pins = Pin.where(category_id: 1).order('created_at DESC')
    length = @pins.length

    @pins = WillPaginate::Collection.create(current_page, per_page, length) do |pager|
      pager.replace @pins[pager.offset, pager.per_page].to_a
    end
  end

  def show
    ids = Pin.pluck(:id).shuffle[0..7]
		@pins = Pin.where(id: ids)
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)

    
      if @pin.save
        redirect_to @pin
      else
        render :new
      end
    
  end

  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # def like
  #   @pin.liked_by current_user
  #   respond_to do |format|
  #     format.html {redirect_to :back}
  #     format.js
  #   end
  # end

  # def dislike
  #   @pin.disliked_by current_user
  #   respond_to do |format|
  #     format.html {redirect_to :back}
  #     format.js
  #   end
  # end

  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end
    
    def correct_pin
      @pin = current_user.pins.find_by(id: params[:id])      
      redirect_to root_url if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:content, :image, :title, :user_id, :category_id)
    end
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/pins/_disqus.html.erb
<div class="container-fluid">
  <div class="col-md-12">
    <h2 class="bold black nunito text-center">Any thoughts?</h2>
    <hr/>
    <div id="disqus_thread"></div>
      <script>
      var disqus_shortname = 'booday10';
      var disqus_identifier = '<%= @pin.id %>';
      var disqus_title = '<%= @pin.title %>';
      var disqus_url = '<%= url_for([@pin, {only_path: false}]) %>';

      (function() { // DON'T EDIT BELOW THIS LINE
      var d = document, s = d.createElement('script');

      s.src = '//booday10.disqus.com/embed.js';

      s.setAttribute('data-timestamp', +new Date());
      (d.head || d.body).appendChild(s);
      })();
      </script>
      <noscript>Please enable JavaScript to view the
        <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a>
      </noscript>
  </div> <!--col-md-12-->
</div> <!--container-fluid-->

app/views/pins/_form.html.erb
<div class="container">
  <div class="row">
    <div class=" col-md-offset-4 col-md-8">
      
      <%= form_for @pin, html: { multipart: true } do |f| %>
        <% if @pin.errors.any? %>
          <ul>
            <% @pin.errors.full_messages.each do |msg| %>
              <li class="danger"><%= msg %></li>
            <% end %>
          </ul>
        <% end %>
      
      <%= f.text_field :title, placeholder: 'Title', class: 'form-control' %>
      <br/>
      <%= f.bootsy_area :content, editor_options: { color: false, link: false, image: false },
                        placeholder: 'Story', rows: 15, class: 'form-control' %>
      <div class="form-group">

        <label class="photo-upload"> 
          <%= f.file_field :image %>
          <i class="glyphicon glyphicon-picture"></i>
        </label>

        <%= f.collection_select(:category_id, Category.order(:name), :id, :name, {prompt: "Category"}, {class: 'form-control'}) %>
      </div>

      <%= f.submit "Save", class: "btn btn-primary btn-lg rway" %>
      <% end %>
    </div> <!--col-md-10-->
  </div> <!--row-->
</div> <!--container-->

app/views/pins/_pin.html.erb
<div class="box panel panel-default">
  <%= link_to image_tag(pin.image.url(:large)), pin unless pin.image.blank? %>
  <div class="panel-body">
    
    <h4 class="bold nunito"><%= link_to pin.title, pin %></h4>
    
  </div> <!--panel-body-->
</div> <!--box-->

app/views/pins/_side_bar.html.erb
<div class="container-fluid">
  <div class="col-md-8 col-md-offset-2">
    <h2 class="bold black nunito text-center">Popular</h2>
    <hr/>
    <div id="pins">
      <% @pins.each do |pin| %>
        <div class="box-sm panel panel-default">
          <%= link_to image_tag(pin.image.url(:large)), pin unless pin.image.blank? %>
          <div class="panel-body">
            <h5 class="bold mclaren"><%= link_to pin.title, pin %></h5>            
          </div> <!--panel-body-->
        </div> <!--box-->
      <% end %>
    </div> <!--pins-->
  </div> <!--col-md-8-->
</div> <!--container-fluid-->

app/views/pins/basket_ball.html.erb
<div class="container-fluid">
  <div class="col-md-10 col-md-offset-1">
    <% unless @pins.blank? %>
      <div id="pins">
        <%= render @pins %>
      </div> <!--pins-->
      <div class="text-center">
        <%= will_paginate @pins, renderer: BootstrapPagination::Rails %>
      </div>
    <% else %>
      <div class="col-md-offset-3 col-md-6 text-center no-stories">
  			<h3>There are no stories matching your search.</h3>
	      <h4>Please modify your search phrase and try again.</h4>
  		</div>
    <% end %>
  </div> <!--col-md-10-->
</div> <!--container-fluid-->

app/views/pins/dislike.js.erb
$("#dislikes_count_<%= @pin.id %>").html('<%= @pin.cached_votes_down %>');
$("#likes_count_<%= @pin.id %>").html('<%= @pin.cached_votes_up %>');
$("#dislikes_count_<%= @pin.id %>").hide().fadeIn(2000);

app/views/pins/edit.html.erb
<%= render 'form', title: "#{@pin.title}" %>

app/views/pins/index.html.erb
<div class="container-fluid">
  <div class="col-md-10 col-md-offset-1">
    <% unless @pins.blank? %>
      <div id="pins">
        <%= render @pins %>
      </div> <!--pins-->
      <div class="text-center">
        <%= will_paginate @pins, renderer: BootstrapPagination::Rails %>
      </div>
    <% else %>
      <div class="col-md-offset-3 col-md-6 text-center no-stories">
  			<h3>There are no stories matching your search.</h3>
	      <h4>Please modify your search phrase and try again.</h4>
  		</div>
    <% end %>
  </div> <!--col-md-10-->
</div> <!--container-fluid-->

app/views/pins/like.js.erb
$("#likes_count_<%= @pin.id %>").html('<%= @pin.cached_votes_up %>');
$("#dislikes_count_<%= @pin.id %>").html('<%= @pin.cached_votes_down %>');
$("#likes_count_<%= @pin.id %>").hide().fadeIn(2000);

app/views/pins/new.html.erb
<%= render 'form', title: "Publish" %>

app/views/pins/show.html.erb
<% provide(:title, "#{@pin.title}") %>
<% provide(:pin_image_url, "#{@pin.image.url(:large)}") %>
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <div class="panel panel-default">
        <p class="text-left">
          <%= image_tag @pin.image.url(:large), class: "img-responsive", style: "width: 100%;" unless @pin.image.blank? %>
        </p>
        <div class="panel-body">
          <h3 class="bold black nunito text-left"><%= @pin.title %></h3>
          <span id="article"><%= simple_format @pin.content %></span>
          <div class="col-md-offset-4 col-md-6">
            <div class="btn btn-group">
              <% if logged_in? %>
                <%= link_to edit_pin_path(@pin), class: "btn btn-primary rway" do %>
                  Edit
                <% end %>
                <%= link_to @pin, class: "btn btn-danger", method: :delete, data: { confirm: "This action is permanent." } do %>
                  <i class="glyphicon glyphicon-trash"></i>
                <% end %>
              <% end %>        
            </div>
          </div>
          <%= social_share_button_tag(@pin.title, image: @pin.image.url, popup: "true") %>
        </div>
      </div> <!--panel-->
      <!-- < render 'disqus' > -->
    </div> <!--col-md-8-->
    <div class="col-md-4">
      <%= render 'side_bar' %>
    </div> <!--col-md-4-->
  </div> <!--row-->
</div>

app/views/pins/soccer.html.erb
<div class="container-fluid">
  <div class="col-md-10 col-md-offset-1">
    <% unless @pins.blank? %>
      <div id="pins">
        <%= render @pins %>
      </div> <!--pins-->
      <div class="text-center">
        <%= will_paginate @pins, renderer: BootstrapPagination::Rails %>
      </div>
    <% else %>
      <div class="col-md-offset-3 col-md-6 text-center no-stories">
  			<h3>There are no stories matching your search.</h3>
	      <h4>Please modify your search phrase and try again.</h4>
  		</div>
    <% end %>
  </div> <!--col-md-10-->
</div> <!--container-fluid-->