config/routes.rb
Booday10::Application.routes.draw do

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  root 'pins#index'
  get 'soccer' => 'pins#soccer'
  get 'basket_ball' => 'pins#basket_ball'
  get 'login' => 'sessions#new'
  get 'signup' => 'users#new'
  post 'login' => 'sessions#create'
  post 'signup' => 'users#create'
  delete 'logout' => 'sessions#destroy'
    
  resources :users
  resources :pins
  # resources :pins do
  #   member do
  #     put "like" => "pins#like"
  #     put "dislike" => "pins#dislike"
  #   end
  # end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default custom-nav navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- < link_to 'Booday10', root_path, class: "navbar-brand" > -->
      <%= link_to root_path, class: "navbar-brand" do %>
        <i>Booday</i><i style="color:#1abc9c;">10</i>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <li>
          <%= link_to root_path, class: "rway" do %>
            <strong> Home </strong>
          <% end %>
        </li>
        <li>
          <%= link_to soccer_path, class: "rway" do %>
            <strong> Soccer </strong>
          <% end %>
        </li>
        <li>
          <%= link_to basket_ball_path, class: "rway" do %>
            <strong> Basket ball </strong>
          <% end %>
        </li>

        <% if logged_in? %>
        <!--<li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>-->
          <li>
            <%= link_to new_pin_path, class: "rway" do %>
              <strong> Publish </strong>
            <% end %>
          </li>

          <li>
            <%= link_to logout_path, method: "delete", class: "rway" do %>
              <strong> Exit </strong>
            <% end %>
          </li>
        <!--<li class="dropdown">-->
        <!--  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>-->
        <!--  <ul class="dropdown-menu">-->
        <!--    <li><a href="#">Action</a></li>-->
        <!--    <li><a href="#">Another action</a></li>-->
        <!--    <li><a href="#">Something else here</a></li>-->
        <!--    <li role="separator" class="divider"></li>-->
        <!--    <li><a href="#">Separated link</a></li>-->
        <!--    <li role="separator" class="divider"></li>-->
        <!--    <li><a href="#">One more separated link</a></li>-->
        <!--  </ul>-->
        <!--</li>-->
        <% end %>
      </ul>

      <%= form_tag(root_path, method: "get", class: "navbar-form navbar-right") do %>      
        <div class="input-group">
          <%= text_field_tag :search, params[:search], placeholder: "Search", class: "form-control", size: "30" %>          
          <span class="input-group-btn">
            <%= button_tag(type: "submit", class: "btn btn-default push-down") do %>
                <span class="glyphicon glyphicon-search"></span>
            <% end %>
          </span>
        </div>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <!--<li><a href="#">Link</a></li>-->
        <!--<li class="dropdown">-->
        <!--  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>-->
        <!--  <ul class="dropdown-menu">-->
        <!--    <li><a href="#">Action</a></li>-->
        <!--    <li><a href="#">Another action</a></li>-->
        <!--    <li><a href="#">Something else here</a></li>-->
        <!--    <li role="separator" class="divider"></li>-->
        <!--    <li><a href="#">Separated link</a></li>-->
        <!--  </ul>-->
        <!--</li>-->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta property="og:title" content="<%= @pin.title if @pin %>" />
    <meta property="og:image" content="<%= @pin.image.url if @pin %>" />
    
    <title><%= full_title(yield(:title)) %></title>

    <%= favicon_link_tag(source='favicon.ico', options={}) %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  	
  	<%= render 'layouts/nav' %>
  	
    	<!-- flash ordinarily goes here -->
    
    	<%= yield %>
  	</div>
  </body>
</html>